ALTER TABLE STUDENT ALTER COLUMN BIRTHDAY DATE NOT NULL;
ALTER TABLE MARK ADD CHECK (MARK >= 1 AND MARK <= 10);
ALTER TABLE MARK ALTER COLUMN STUDENT_ID BIGINT NOT NULL;
ALTER TABLE MARK ALTER COLUMN SUBJECT_ID BIGINT NOT NULL;
ALTER TABLE SUBJECT ADD CHECK (GRADE >= 1 AND GRADE <= 5);
ALTER TABLE PAYMENTTYPE ADD UNIQUE (NAME);
ALTER TABLE PAYMENT ALTER COLUMN TYPE_ID BIGINT NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN AMOUNT NUMERIC NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN PAYMENT_DATE TIMESTAMP NOT NULL;