SELECT MAX(BIRTHDAY) FROM STUDENT;
SELECT MIN(PAYMENT_DATE) FROM PAYMENT;
SELECT AVG(MARK) FROM MARK WHERE SUBJECT_ID IN (SELECT ID FROM SUBJECT Where NAME = 'Math');
SELECT MIN(AMOUNT) FROM PAYMENT WHERE TYPE_ID IN (SELECT ID FROM PAYMENTTYPE WHERE NAME = 'WEEKLY');